/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHermesReputation,
  IHermesReputationInterface,
} from "../../../contracts/HermesEscrow.sol/IHermesReputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "milestoneId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "wasPositive",
        type: "bool",
      },
      {
        internalType: "string",
        name: "notes",
        type: "string",
      },
    ],
    name: "updateReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHermesReputation__factory {
  static readonly abi = _abi;
  static createInterface(): IHermesReputationInterface {
    return new Interface(_abi) as IHermesReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHermesReputation {
    return new Contract(address, _abi, runner) as unknown as IHermesReputation;
  }
}
