/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace HermesReputation {
  export type AgentIdentityStruct = {
    id: BytesLike;
    wallet: AddressLike;
    name: string;
    role: string;
    metadataUri: string;
    reputationScore: BigNumberish;
    totalJobs: BigNumberish;
    completedJobs: BigNumberish;
    registeredAt: BigNumberish;
    isVerified: boolean;
  };

  export type AgentIdentityStructOutput = [
    id: string,
    wallet: string,
    name: string,
    role: string,
    metadataUri: string,
    reputationScore: bigint,
    totalJobs: bigint,
    completedJobs: bigint,
    registeredAt: bigint,
    isVerified: boolean
  ] & {
    id: string;
    wallet: string;
    name: string;
    role: string;
    metadataUri: string;
    reputationScore: bigint;
    totalJobs: bigint;
    completedJobs: bigint;
    registeredAt: bigint;
    isVerified: boolean;
  };

  export type ReputationEventStruct = {
    jobId: BigNumberish;
    milestoneId: BigNumberish;
    wasPositive: boolean;
    timestamp: BigNumberish;
    notes: string;
  };

  export type ReputationEventStructOutput = [
    jobId: bigint,
    milestoneId: bigint,
    wasPositive: boolean,
    timestamp: bigint,
    notes: string
  ] & {
    jobId: bigint;
    milestoneId: bigint;
    wasPositive: boolean;
    timestamp: bigint;
    notes: string;
  };
}

export interface HermesReputationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "escrowContract"
      | "getAgent"
      | "getAgentByWallet"
      | "getAgentId"
      | "getReputationHistory"
      | "isRegistered"
      | "owner"
      | "registerAgent"
      | "setEscrowContract"
      | "updateReputation"
      | "verifyAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentVerified"
      | "EscrowContractSet"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "escrowContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAgentByWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [BytesLike, BigNumberish, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "escrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgentId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReputationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    wallet: AddressLike,
    name: string,
    role: string
  ];
  export type OutputTuple = [
    agentId: string,
    wallet: string,
    name: string,
    role: string
  ];
  export interface OutputObject {
    agentId: string;
    wallet: string;
    name: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVerifiedEvent {
  export type InputTuple = [agentId: BytesLike, wallet: AddressLike];
  export type OutputTuple = [agentId: string, wallet: string];
  export interface OutputObject {
    agentId: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowContractSetEvent {
  export type InputTuple = [escrowContract: AddressLike];
  export type OutputTuple = [escrowContract: string];
  export interface OutputObject {
    escrowContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    jobId: BigNumberish,
    milestoneId: BigNumberish,
    wasPositive: boolean,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    jobId: bigint,
    milestoneId: bigint,
    wasPositive: boolean,
    newScore: bigint
  ];
  export interface OutputObject {
    agentId: string;
    jobId: bigint;
    milestoneId: bigint;
    wasPositive: boolean;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HermesReputation extends BaseContract {
  connect(runner?: ContractRunner | null): HermesReputation;
  waitForDeployment(): Promise<this>;

  interface: HermesReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  escrowContract: TypedContractMethod<[], [string], "view">;

  getAgent: TypedContractMethod<
    [agentId: BytesLike],
    [HermesReputation.AgentIdentityStructOutput],
    "view"
  >;

  getAgentByWallet: TypedContractMethod<
    [wallet: AddressLike],
    [HermesReputation.AgentIdentityStructOutput],
    "view"
  >;

  getAgentId: TypedContractMethod<[wallet: AddressLike], [string], "view">;

  getReputationHistory: TypedContractMethod<
    [agentId: BytesLike],
    [HermesReputation.ReputationEventStructOutput[]],
    "view"
  >;

  isRegistered: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [name: string, role: string, metadataUri: string],
    [string],
    "nonpayable"
  >;

  setEscrowContract: TypedContractMethod<
    [_escrow: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [
      agentId: BytesLike,
      jobId: BigNumberish,
      milestoneId: BigNumberish,
      wasPositive: boolean,
      notes: string
    ],
    [void],
    "nonpayable"
  >;

  verifyAgent: TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "escrowContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [HermesReputation.AgentIdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByWallet"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [HermesReputation.AgentIdentityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentId"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getReputationHistory"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [HermesReputation.ReputationEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, role: string, metadataUri: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEscrowContract"
  ): TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      jobId: BigNumberish,
      milestoneId: BigNumberish,
      wasPositive: boolean,
      notes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentVerified"
  ): TypedContractEvent<
    AgentVerifiedEvent.InputTuple,
    AgentVerifiedEvent.OutputTuple,
    AgentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowContractSet"
  ): TypedContractEvent<
    EscrowContractSetEvent.InputTuple,
    EscrowContractSetEvent.OutputTuple,
    EscrowContractSetEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(bytes32,address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentVerified(bytes32,address)": TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;
    AgentVerified: TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;

    "EscrowContractSet(address)": TypedContractEvent<
      EscrowContractSetEvent.InputTuple,
      EscrowContractSetEvent.OutputTuple,
      EscrowContractSetEvent.OutputObject
    >;
    EscrowContractSet: TypedContractEvent<
      EscrowContractSetEvent.InputTuple,
      EscrowContractSetEvent.OutputTuple,
      EscrowContractSetEvent.OutputObject
    >;

    "ReputationUpdated(bytes32,uint256,uint256,bool,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
