/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HermesEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelJob"
      | "createJob"
      | "getJob"
      | "getJobsByClient"
      | "getJobsByFreelancer"
      | "getMilestone"
      | "jobCounter"
      | "lockedAmount"
      | "refundClient"
      | "rejectMilestone"
      | "releaseMilestone"
      | "reputation"
      | "submitMilestone"
      | "updateVerifier"
      | "usdc"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClientRefunded"
      | "JobCancelled"
      | "JobCompleted"
      | "JobCreated"
      | "MilestoneRejected"
      | "MilestoneReleased"
      | "MilestoneSubmitted"
      | "VerifierUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [
      AddressLike,
      string,
      string,
      string[],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobsByClient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobsByFreelancer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockedAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundClient",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobsByClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobsByFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobCounter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace ClientRefundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, client: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish, client: AddressLike];
  export type OutputTuple = [jobId: bigint, client: string];
  export interface OutputObject {
    jobId: bigint;
    client: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike
  ];
  export type OutputTuple = [jobId: bigint, client: string, freelancer: string];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    freelancer: AddressLike,
    title: string,
    totalAmount: BigNumberish,
    freelancerERC8004Id: BytesLike,
    clientERC8004Id: BytesLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    freelancer: string,
    title: string,
    totalAmount: bigint,
    freelancerERC8004Id: string,
    clientERC8004Id: string
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    freelancer: string;
    title: string;
    totalAmount: bigint;
    freelancerERC8004Id: string;
    clientERC8004Id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRejectedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    milestoneId: BigNumberish,
    freelancer: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    milestoneId: bigint,
    freelancer: string
  ];
  export interface OutputObject {
    jobId: bigint;
    milestoneId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    milestoneId: BigNumberish,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    milestoneId: bigint,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    milestoneId: bigint;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    milestoneId: BigNumberish,
    freelancer: AddressLike,
    deliverableUrl: string,
    submittedAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    milestoneId: bigint,
    freelancer: string,
    deliverableUrl: string,
    submittedAt: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    milestoneId: bigint;
    freelancer: string;
    deliverableUrl: string;
    submittedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdatedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HermesEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): HermesEscrow;
  waitForDeployment(): Promise<this>;

  interface: HermesEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [
      freelancer: AddressLike,
      title: string,
      description: string,
      milestoneDescriptions: string[],
      milestoneAmounts: BigNumberish[],
      freelancerERC8004Id: BytesLike,
      clientERC8004Id: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        client: string;
        freelancer: string;
        title: string;
        description: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        status: bigint;
        createdAt: bigint;
        milestoneCount: bigint;
        erc8004FreelancerId: string;
        erc8004ClientId: string;
      }
    ],
    "view"
  >;

  getJobsByClient: TypedContractMethod<
    [client: AddressLike],
    [bigint[]],
    "view"
  >;

  getJobsByFreelancer: TypedContractMethod<
    [freelancer: AddressLike],
    [bigint[]],
    "view"
  >;

  getMilestone: TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint] & {
        description: string;
        amount: bigint;
        status: bigint;
        deliverableUrl: string;
        submittedAt: bigint;
        releasedAt: bigint;
      }
    ],
    "view"
  >;

  jobCounter: TypedContractMethod<[], [bigint], "view">;

  lockedAmount: TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;

  refundClient: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectMilestone: TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseMilestone: TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  reputation: TypedContractMethod<[], [string], "view">;

  submitMilestone: TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish, deliverableUrl: string],
    [void],
    "nonpayable"
  >;

  updateVerifier: TypedContractMethod<
    [newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      freelancer: AddressLike,
      title: string,
      description: string,
      milestoneDescriptions: string[],
      milestoneAmounts: BigNumberish[],
      freelancerERC8004Id: BytesLike,
      clientERC8004Id: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        client: string;
        freelancer: string;
        title: string;
        description: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        status: bigint;
        createdAt: bigint;
        milestoneCount: bigint;
        erc8004FreelancerId: string;
        erc8004ClientId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobsByClient"
  ): TypedContractMethod<[client: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getJobsByFreelancer"
  ): TypedContractMethod<[freelancer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint] & {
        description: string;
        amount: bigint;
        status: bigint;
        deliverableUrl: string;
        submittedAt: bigint;
        releasedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockedAmount"
  ): TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundClient"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectMilestone"
  ): TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<
    [jobId: BigNumberish, milestoneId: BigNumberish, deliverableUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateVerifier"
  ): TypedContractMethod<[newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ClientRefunded"
  ): TypedContractEvent<
    ClientRefundedEvent.InputTuple,
    ClientRefundedEvent.OutputTuple,
    ClientRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRejected"
  ): TypedContractEvent<
    MilestoneRejectedEvent.InputTuple,
    MilestoneRejectedEvent.OutputTuple,
    MilestoneRejectedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdated"
  ): TypedContractEvent<
    VerifierUpdatedEvent.InputTuple,
    VerifierUpdatedEvent.OutputTuple,
    VerifierUpdatedEvent.OutputObject
  >;

  filters: {
    "ClientRefunded(uint256,address,uint256)": TypedContractEvent<
      ClientRefundedEvent.InputTuple,
      ClientRefundedEvent.OutputTuple,
      ClientRefundedEvent.OutputObject
    >;
    ClientRefunded: TypedContractEvent<
      ClientRefundedEvent.InputTuple,
      ClientRefundedEvent.OutputTuple,
      ClientRefundedEvent.OutputObject
    >;

    "JobCancelled(uint256,address)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCompleted(uint256,address,address)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,string,uint256,bytes32,bytes32)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "MilestoneRejected(uint256,uint256,address)": TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;
    MilestoneRejected: TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;

    "MilestoneReleased(uint256,uint256,address,uint256)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;

    "MilestoneSubmitted(uint256,uint256,address,string,uint256)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "VerifierUpdated(address,address)": TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;
    VerifierUpdated: TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;
  };
}
